### ISSUE TITLE
plugin use own dependencies

### ISSUE THREAD

**Issue by dbrezoev** [aurelia/skeleton-plugin#29]
Hi, I know this is not an issue, but I thought here is the right place to ask this question, after some tryings in the gitter channel. 
So I make a plugin which uses moment js as dependency. But when I installed this plugin it wants moment to be installed in the global project. How can I say to my plugin when I "import moment from 'moment'" I need to load it from its own dependencies. I asked this question also here: 
[http://patrickwalters.net/making-out-first-plugin/](url) Thanks in advance

**Comment by EisenbergEffect** [comment]
The problem is that JSPM doesn't make all dependencies available from any module by default. It's a poor design decision in my opinion and its very unintuitive. To change this in jspm 0.16 you have to install the dependency as a top-level dependency in your project. With jspm 0.17 you can actually specify it as a peerDependency in your plugin, which will cause it to be installed as a top level dependency when your plugin is added to a project. Take a look at some of the package.json files for aurelia's libraries. We have set things up to handle all situations, so that if using jspm 0.16 things work as previous, but if using 0.17 peer deps get installed.

**Comment by dbrezoev** [comment]
Thanks for the quick response
